#Download files
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/README.md"                   , "README.md"                   )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Info.plist"         , "Contents/Info.plist"         )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/DefaultPrefs.json"  , "Contents/DefaultPrefs.json"  )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/__init__.py"   , "Contents/Code/__init__.py"   )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/common.py"     , "Contents/Code/common.py"     )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/AnimeLists.py" , "Contents/Code/AnimeLists.py" )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/AniDB.py"      , "Contents/Code/AniDB.py"      )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/TheTVDB.py"    , "Contents/Code/TheTVDB.py"    )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/FanartTV.py"   , "Contents/Code/FanartTV.py"   )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/TheMovieDb.py" , "Contents/Code/TheMovieDb.py" )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/MyAnimeList.py", "Contents/Code/MyAnimeList.py")
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/TVTunes.py"    , "Contents/Code/TVTunes.py")
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/OMDb.py"       , "Contents/Code/OMDb.py"       )
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/ZeroQI/Hama.bundle/master/Contents/Code/Plex.py"       , "Contents/Code/Plex.py"       )
